name: urn:sib:product-relations-1
version: 1
state: Experimental
description: |
  Contains information about relations to other products like spareparts,
  accessories, components or successors.
fields:
  successors:
    type: List
    description: Lists all successors of this product.
    optional: true
    maxOccur: 10
    contents:
      type: Object
      fields:
        itemNumber:
          type: String
          description: Contains the item number of the successor.
        type:
          type: String
          description: |
            Describes whether this successor is a sort of drop-in replacement
            or more or less a similar product which might be used but may come
            with some complexity during installation.
          choices:
            - DIRECT_REPLACEMENT
            - SIMILAR_PRODUCT

  spareparts:
    type: List
    description: |
      Lists modules which may define explosion drawings or other schematics along
      with lists of associated spareparts.
    optional: true
    contents:
      type: Object
      fields:
        module:
          type: String
          description: Contains a short and concise name or description of the module.
          translatable: true
          optional: true
        drawings:
          type: List
          description: Contains one or more drawings.
          optional: true
          contents:
            type: Object
            fields:
              label:
                type: String
                description: Contains the name or description of this drawing.
                translatable: true
                optional: true
              image:
                type: Asset
                description: Contains the name or path of the asset to use as drawing.
                acceptedFileExtensions:
                  - pdf
                  - jpg
                  - jpeg
                  - png
                  - tif
                  - tiff
                  - webp
                  - heic
                  - avif
        parts:
          type: List
          description: Lists the spareparts of the module.
          contents:
            type: Object
            fields:
              number:
                type: String
                description: Contains the number or marking of the sparepart in the drawing.
                optional: true
              itemNumber:
                type: String
                description: Contains the item number of the sparepart.
              shortDescription:
                type: String
                description: Contains a short and concise description or remark for the part.
                optional: true
                translatable: true

  accessories:
    type: List
    optional: true
    maxOccur: 250
    description: Lists all compatible accessories for this product.
    contents:
      type: Object
      fields:
        itemNumber:
          type: String
          description: Item number of the accessory.
        shortDescription:
          type: String
          optional: true
          translatable: true
          description: Short, display-friendly name or description of the accessory.
        recommendedQuantity:
          type: Number
          optional: true
          description: Quantity of this accessory typically used or recommended for use with the product.
        group:
          type: String
          optional: true
          translatable: true
          description: Logical accessory group this item belongs to (e.g., "Mounting", "Electrical components").
        type:
          type: String
          optional: true
          description: Describes the accessory type or intended use.
          choices:
            - optional
            - mandatory

  components:
    type: List
    optional: true
    description: Lists the components that are part of this product if it is a set or kit.
    contents:
      type: Object
      fields:
        itemNumber:
          type: String
          description: Item number of the component within the set.
        shortDescription:
          type: String
          optional: true
          translatable: true
          description: Short, display-friendly name of the set component.
        quantity:
          type: Number
          description: Quantity of this component in the set.
