name: urn:sib:product-logistics-1
version: 1
description: Provides information about transportation and storage of a product.
state: Experimental
fields:
  shelfLife:
    type: Number
    optional: true
    description: Contains the expected shelf life in months.
  numberOfPackages:
    type: Number
    optional: true
    description: |
      Contains the number of packages used for this product. If the product is delivered in
      a single package, it is recommended to leave this field empty.
  basePackage:
    type: Object
    description: Contains information about the product within its basic packaging.
    fields:
      length:
        type: Number
        optional: true
        description: Contains the length of the product within its base packaging in millimeters.
      width:
        type: Number
        optional: true
        description: Contains the width of the product within its base packaging in millimeters.
      height:
        type: Number
        optional: true
        description: Contains the height of the product within its base packaging in millimeters.
      weight:
        type: Number
        optional: true
        description: Contains the weight of the product with packaging in kilograms.
  dangerousGoods:
    type: Object
    description: |
      Determines if this product is or contains dangerous goods to ensure a safe transportation
      and storage.
    optional: true
    fields:
      containsDangerousGoods:
        type: Boolean
        description: Determines if this product is or contains dangerous goods.
        optional: true
      unNumbers:
        type: List
        description: Contains the UN numbers of the hazardous materials within the product.
        optional: true
        contents: 
          type: String
      hazardClass:
        type: String
        description: Contains the hazard class of this product or its materials, e.g. "3" for flammable liquids.
        optional: true
      hazardDivision:
        type: String
        optional: true
        description: Division within the hazard class, e.g. "1.4" for explosives.
      transportCategory:
        type: String
        description: Contains the transportation category of this product or its materials.
        optional: true
      hazardIdentificationNumber:
        type: String
        description: |
          Contains the ADR hazard identification number (HIN), also known as the Kemler code, shown on orange panels during transport.
        optional: true
      packingGroup:
        type: String
        optional: true
        description: Contains the ADR packing group of the hazardous substance, e.g. "II".
      properShippingName:
        type: String
        optional: true
        description: Official UN shipping name of the hazardous material.
        translatable: true
      technicalName:
        type: String
        optional: true
        description: Technical name for the dangerous substance, if required (e.g. for N.O.S. entries).
        translatable: true
      hazardLabels:
        type: List
        optional: true
        description: List of hazard labels (Gefahrenzettel) applicable for the product (e.g. "3", "8").
        contents:
          type: String
      numberOfPackages:
        type: Number
        optional: true
        description: Total number of dangerous goods packages for this product.
      packageDescription:
        type: String
        optional: true
        description: Description of the dangerous goods packaging used (it is recomended to use the codes of ADR 6.1.2 Code for designating types of packagings).
      tunnelRestrictionCode:
        type: String
        optional: true
        description: ADR tunnel restriction code (e.g. "E", "D/E") indicating transport limitations in tunnels.
      waterHazardClass:
        type: String
        optional: true
        description: Water hazard classification (WGK) according to German regulations.
      limitedQuantity:
        type: Boolean
        optional: true
        description: Indicates whether the product is subject to ADR limited quantity exemptions.
      batteryWeight:
        type: Number
        optional: true
        description: Weight of the battery if it contributes to the dangerous goods classification, in kilograms.
