name: urn:sib:product-lca-1
version: 1
state: Experimental
description: |
  Life Cycle Assessment (LCA) data block according to EN 15804:2012+A2:2019/AC:2021,
  ISO 14025 and ISO 21930. Covers declared units, functional description, 
  reference service life, optional scenarios and environmental impact 
  indicators across all life cycle stages (A1–A3, A4–C4, D). Fully compatible 
  with ECO Platform Digital EPDs and the INData 2.0 data model.

fields:

  epdId:
    type: String
    optional: true
    description: |
      ILCD UUID of the EPD process dataset. Ensures unique identification 
      and stable referencing between product data and environmental data.

  epdVersion:
    type: String
    optional: true
    description: Version string of the EPD dataset (e.g., 00.01.000) in correspondence to the epdId.

  registrationNumber:
    type: String
    optional: true
    description: |
      Public registration number assigned by the programme operator
      (e.g., "EPD-IES-0026045:001"). Used for official referencing and
      verification of the EPD in the programme operator's registry.

  programmeOperator:
    type: String
    optional: true
    description: |
      Name of the programme operator that published and registered the EPD
      (e.g., "The International EPD System", "IBU", "BRE"). Required to
      identify the governing programme and its specific rules (PCR) under
      which the EPD was created and verified.

  title:
    type: String
    optional: true
    description: Human-readable title of the EPD as stated in the dataset.
    translated: true
  
  publishedAt:
    type: Date
    optional: true
    description: |
      Initial publication date of the EPD (referred to as "initial version date"
      by EPD International). Needed for version tracking and regulatory conformity.

  versionDate:
    type: Date
    optional: true
    description: |
      Date of the most recent revision of the EPD (referred to as "version date"
      by EPD International). Only applicable when the EPD has been updated after
      its initial publication. If the EPD has never been revised, this field
      should be omitted.

  validTo:
    type: Date
    optional: true
    description: |
      End of the EPD validity period. EPDs can only be used within their 
      declared validity window to ensure legal and methodological correctness.  

  declaredUnitQuantity:
    type: Number
    optional: true
    description: |
      Declared quantity to which all environmental impacts refer (EN 15804 §5.3.2 + §6.3.4).
      Required when the EPD uses a declared unit. Some EPDs use only a functional unit instead.

  declaredUnitUnit:
    type: String
    optional: true
    description: |
      Unit of the declared quantity according to EN 15804. Defines the
      reference basis of all environmental indicators when using a declared unit.
    choices:
      - PCE   # Functional or discrete products
      - KGM   # Weight-based materials
      - MTK   # Surface-based building products
      - MTQ   # Volumetric materials
      - MTR   # Linear products
      - KWH   # Energy-delivering products
      - SET   # Installation sets or kits

  functionalUnitQuantity:
    type: Number
    optional: true
    description: |
      Quantity of the functional unit to which all environmental impacts refer (EN 15804 §5.3).
      Required when the EPD uses a functional unit. An EPD may provide both a declared
      and a functional unit simultaneously.

  functionalUnitUnit:
    type: String
    optional: true
    description: |
      Unit of the functional unit according to EN 15804.
    choices:
      - PCE   # Functional or discrete products
      - KGM   # Weight-based materials
      - MTK   # Surface-based building products
      - MTQ   # Volumetric materials
      - MTR   # Linear products
      - KWH   # Energy-delivering products
      - SET   # Installation sets or kits

  functionalUnitDescription:
    type: String
    optional: true
    description: |
      Human-readable description of the functional unit, including performance
      characteristics and reference service life where applicable (EN 15804 §5.3).

  referenceServiceLife:
    type: Number
    optional: true
    description: Expected service life of the product in years. (EN 15804 §6.3.8)

  thirdPartyVerification:
    type: String
    optional: true
    description: how ist this epd verified?
    choices:
      - none
      - internal
      - external

  scenarios:
    type: List
    optional: true
    description: List of alternative scenarios defined by the EPD. (EN 15804 §6.3.7)
    contents:
      type: Object
      fields:
        id:
          type: String
          description: Scenario identifier, e.g., "S1".

        description:
          type: String
          translated: true
          optional: true
          description: Human-readable scenario description in multiple languages.

  impacts:
    type: List
    optional: true
    description: |
      Environmental impact indicators per life cycle stage according to EN 15804+A2.
      All values refer to the declared unit. If no declared unit is provided,
      values refer to the functional unit.
    contents:
      type: Object
      fields:

        stage:
          type: String
          description: Life cycle stage according to EN 15804 Table 2.
          choices:
            # PRODUCT STAGE
            - A1   # Raw material supply
            - A2   # Transport
            - A3   # Manufacturing

            # CONSTRUCTION STAGE
            - A4   # Transport to construction site
            - A5   # Installation

            # USE STAGE
            - B1   # Use
            - B2   # Maintenance
            - B3   # Repair
            - B4   # Replacement
            - B5   # Refurbishment
            - B6   # Operational energy use
            - B7   # Operational water use

            # END-OF-LIFE STAGE
            - C1   # Deconstruction / demolition
            - C2   # Transport
            - C3   # Waste processing
            - C4   # Disposal

            # BEYOND SYSTEM BOUNDARY
            - D    # Reuse/recovery/recycling benefits

            # AGGREGATED STAGES
            - A1-A3
            - A4-A5
            - B1-B7
            - C1-C4
            - A1-A5
            - A1-D

        declared:
          type: Boolean
          description: |
            Indicates whether this module is declared (true) or 
            marked as “MND – Module not declared” (false).

        scenario:
          type: String
          optional: true
          description: References a scenario ID from scenarios.

        # ---------------------------------------------------------------------
        # === IMPACT INDICATORS ===
        # ---------------------------------------------------------------------

        # --- Climate Change ---
        GWP_FOSSIL:
          type: Number
          optional: true
          description: Climate change from fossil sources [kg CO2-eq].

        GWP_BIOGENIC:
          type: Number
          optional: true
          description: Climate change from biogenic carbon [kg CO2-eq].

        GWP_LULUC:
          type: Number
          optional: true
          description: Climate change from land use and land-use change [kg CO2-eq].

        GWP_TOTAL:
          type: Number
          optional: true
          description: Total climate change impact [kg CO2-eq].

        # --- Ozone Depletion ---
        ODP:
          type: Number
          optional: true
          description: Ozone depletion potential [kg CFC-11-eq].

        # --- Acidification ---
        AP:
          type: Number
          optional: true
          description: Acidification potential [mol H+ eq].

        # --- Eutrophication ---
        EP_FRESHWATER:
          type: Number
          optional: true
          description: Eutrophication freshwater [kg P-eq].

        EP_MARINE:
          type: Number
          optional: true
          description: Eutrophication marine [kg N-eq].

        EP_TERRESTRIAL:
          type: Number
          optional: true
          description: Eutrophication terrestrial [mol N-eq].

        # --- Photochemical Ozone Creation ---
        POCP:
          type: Number
          optional: true
          description: Photochemical ozone creation potential [kg NMVOC-eq].

        # --- Abiotic Resource Depletion (EN 15804 Table 3) ---
        ADP_MINERALS_METALS:
          type: Number
          optional: true
          description: Abiotic depletion potential for non-fossil resources (minerals & metals) [kg Sb-eq].

        ADP_FOSSIL:
          type: Number
          optional: true
          description: Abiotic depletion potential for fossil resources [MJ, net calorific value].          

        # --- Primary Energy Use ---
        PERE:
          type: Number
          optional: true
          description: Renewable primary energy as energy carrier [MJ].

        PERM:
          type: Number
          optional: true
          description: Renewable primary energy as material [MJ].

        PERT:
          type: Number
          optional: true
          description: Renewable primary energy, total [MJ].

        PENRE:
          type: Number
          optional: true
          description: Non-renewable primary energy as energy carrier [MJ].

        PENRM:
          type: Number
          optional: true
          description: Non-renewable primary energy as material [MJ].

        PENRT:
          type: Number
          optional: true
          description: Non-renewable primary energy, total [MJ].

        # --- Secondary Resources ---
        SM:
          type: Number
          optional: true
          description: Secondary material input [kg].

        RSF:
          type: Number
          optional: true
          description: Renewable secondary fuels [MJ].

        NRSF:
          type: Number
          optional: true
          description: Non-renewable secondary fuels [MJ].

        # --- Water Use ---
        FW:
          type: Number
          optional: true
          description: Use of net fresh water [m3].

        WDP:
          type: Number
          optional: true
          description: Water deprivation potential [m3 world-eq deprived].

        # --- Waste Categories ---
        HWD:
          type: Number
          optional: true
          description: Hazardous waste disposed [kg].

        NHWD:
          type: Number
          optional: true
          description: Non-hazardous waste disposed [kg].

        RWD:
          type: Number
          optional: true
          description: Radioactive waste disposed [kg].

        # --- Output Flows ---
        CRU:
          type: Number
          optional: true
          description: Components for reuse [kg].

        MFR:
          type: Number
          optional: true
          description: Materials for recycling [kg].

        MER:
          type: Number
          optional: true
          description: Materials for energy recovery [kg].

        EEE:
          type: Number
          optional: true
          description: Exported electrical energy [MJ].

        EET:
          type: Number
          optional: true
          description: Exported thermal energy [MJ].

        # --- Additional LCIA Indicators ---
        PM:
          type: Number
          optional: true
          description: Particulate matter formation [Disease incidence].

        IR:
          type: Number
          optional: true
          description: Ionising radiation [kBq U-235-eq].

        ETP_FW:
          type: Number
          optional: true
          description: Ecotoxicity freshwater [CTUe].

        HTP_C:
          type: Number
          optional: true
          description: Human toxicity, cancer effects [CTUh].

        HTP_NC:
          type: Number
          optional: true
          description: Human toxicity, non-cancer effects [CTUh].

        SQP:
          type: Number
          optional: true
          description: Soil quality potential [dimensionless].
