name: urn:sib:product-brand-1
version: 1
state: Experimental
description: |
  Contains some information for the brand or manufacturer of a product.
  This is most probably stored in an own block and then 'linked' to all
  products (sold via one brand - there might by several). This way, the
  information provided below, can be easily changed for all products.
fields:
  brandName:
    type: String
    description: Contains the (short) brand name under which a product is sold.
    optional: true
  brandLogo:
    type: Asset
    description: Contains the logo used for the brand.
    optional: true
    acceptedFileExtensions:
      - jpg
      - jpeg
      - png
      - tif
      - tiff
      - webp
      - heic
      - avif
  slogan:
    type: String
    description: Contains the slogan or tagline of the brand.
    translatable: true
    optional: true
  website:
    type: String
    description: Contains the website URL of the brand or manufacturer. This should be a full URL including "https://".
    translatable: true
    optional: true
  manufacturerName:
    type: String
    description: Should contain the name for contacting the brand manufacturer, according to GPSR regulation.
    translatable: true
    optional: true
  manufacturerPostalAddress:
    type: String
    description: Should contain the postal address for contacting the brand manufacturer, according to GPSR regulation.
    optional: true
  manufacturerElectronicAddress:
    type: String
    description: Should contain the electronic address (e.g. website, email) for contacting the brand manufacturer, according to GPSR regulation.
    optional: true
  distributorName:
    type: String
    description: Should contain the name for contacting the brand distributor, according to GPSR regulation.
    translatable: true
    optional: true
  distributorPostalAddress:
    type: String
    description: Should contain the postal address for contacting the brand distributor, according to GPSR regulation.
    optional: true
  distributorElectronicAddress:
    type: String
    description: Should contain the electronic address (e.g. website, email) for contacting the brand distributor, according to GPSR regulation.
    optional: true