name: urn:sib:product-features-1
version: 1
state: Experimental
fields:
  systems:
    type: List
    contents: 
      type: Object
      fields:
        systemName:
          type: String
          pattern: "[A-Z]{1,20}"
        systemVersion:
          type: String
          pattern: "[1-9][0-9]{0,2}(\\.[0-9]{1,2})"
        classification:
          type: String
        features:
          type: List
          contents: 
            type: Object
            fields:
              name:
                type: String
              value:
                type: String
              unit:
                type: String
                optional: true

  