name: urn:sib:product-logistics-1
version: 1
description: Provides information about transportation and storage of a product.
state: Active
fields:
  shelfLife:
    type: Number
    description: Contains the expected shelf life in months.
    optional: true
    minValue: "0.01"
    maxScale: 2
    softFail: true
  numberOfPackages:
    type: Number
    description: |
      Contains the number of packages used for this product. If the product is delivered in
      a single package, it is recommended to leave this field empty.
    optional: true
    minValue: "1"
    maxScale: 0
  basePackage:
    type: Object
    description: Contains information about the product within its basic packaging.
    optional: true
    fields:
      length:
        type: Number
        optional: true
        description: Contains the length of the product within its base packaging in millimeters.
        minValue: "1"
        maxScale: 1
        softFail: true
      width:
        type: Number
        optional: true
        description: Contains the width of the product within its base packaging in millimeters.
        minValue: "1"
        maxScale: 1
        softFail: true
      height:
        type: Number
        optional: true
        description: Contains the height of the product within its base packaging in millimeters.
        minValue: "1"
        maxScale: 1
        softFail: true
      weight:
        type: Number
        optional: true
        description: Contains the weight of the product with packaging in kilograms.
        minValue: "0.001"
        maxScale: 3
        softFail: true
  dangerousGoods:
    type: Object
    description: |
      Determines if this product is or contains dangerous goods to ensure a safe transportation
      and storage.
    optional: true
    fields:
      containsDangerousGoods:
        type: Boolean
        description: Determines if this product is or contains dangerous goods.
        optional: true
      unNumbers:
        type: List
        description: List of UN numbers for hazardous goods. Each entry must be a four-digit number without prefix (e.g. "1203" for gasoline).
        optional: true
        contents:
          type: String
          pattern: "\\d{4}"
          validationMessage: Must be a 4-digit UN number (e.g. "1203") without letters or prefixes like "UN".
          softFail: true
      hazardClass:
        type: String
        description: Contains the hazard class of the material, e.g. "3" for flammable liquids.
        optional: true
        pattern: "[1-9]"
        validationMessage: Hazard class must 1-9.
        softFail: true
      hazardDivision:
        type: String
        optional: true
        description: Division within the hazard class, e.g. "1.4" for explosives.
        pattern: "[1-9](\\.[1-6])?"
        validationMessage: Division must be in the format 'X' or 'X.Y' where X is 1-9 and Y is 1-6.
        softFail: true
      transportCategory:
        type: String
        description: Contains the transportation category of this product or its materials.
        optional: true
        pattern: "[0-4]"
        validationMessage: Transport category must be 0-4.
        softFail: true
      hazardIdentificationNumber:
        type: String
        description: |
          Contains the ADR hazard identification number (HIN), also known as the Kemler code, shown on orange panels during transport.
        optional: true
        pattern: "(X?\\d{2,3})"
        validationMessage: Value must be in the format 'NN' or 'NNN', optionally prefixed by 'X'.
        softFail: true
      packingGroup:
        type: String
        optional: true
        description: Contains the ADR packing group of the hazardous substance, e.g. "II".
        pattern: "[I]{1,3}"
        validationMessage: Packing group must be I, II, or III.
        softFail: true
      properShippingName:
        type: String
        optional: true
        description: Official UN shipping name of the hazardous material.
        translated: true
      technicalName:
        type: String
        optional: true
        description: Technical name for the dangerous substance, if required (e.g. for N.O.S. entries).
        translated: true
      hazardLabels:
        type: List
        optional: true
        description: List of hazard labels (Gefahrenzettel) applicable for the product (e.g. "3", "8").
        contents:
          type: String
          pattern: "(1|\\.[1-3]|3|4\\.[1-3]|5\\.[1-2]|6\\.[1-2]|7|8|9)"
          validationMessage: Hazard label must be one of the recognized ADR hazard labels (e.g. "3", "8").
          softFail: true
      tunnelRestrictionCode:
        type: String
        optional: true
        description: ADR tunnel restriction code (e.g. "E", "D/E") indicating transport limitations in tunnels.
        pattern: "[A-E](/[A-E])?"
        validationMessage: Tunnel restriction code must be a letter A to E, optionally followed by '/A' to '/E'.
        softFail: true
      waterHazardClass:
        type: String
        optional: true
        description: Water hazard classification (WGK) according to German regulations (AwSV / UBA).
        choices:
          - nwg       # not hazardous to water
          - awg       # generally hazardous to water
          - WGK 1     # slightly hazardous to water
          - WGK 2     # obviously hazardous to water
          - WGK 3     # highly hazardous to water
        validationMessage: Water hazard classification (WGK) must be one of 'nwg', 'awg', 'WGK 1', 'WGK 2', or 'WGK 3'.
        softFail: true
      limitedQuantity:
        type: Boolean
        optional: true
        description: Indicates whether the product is subject to ADR limited quantity exemptions.
      limitedQuantityMaxPerPackage:
        type: String
        optional: true
        description: |
          Maximum quantity per inner packaging allowed under LQ exemption (e.g. "1 L", "500 g").
          Only relevant if limitedQuantity is true.
      packageDescription:
        type: String
        optional: true
        description: Description of the dangerous goods packaging used (it is recomended to use the codes of ADR 6.1.2 Code for designating types of packagings).
      numberOfPackages:
        type: Number
        optional: true
        description: Total number of dangerous goods packages for this product.
        minValue: "1"
        maxScale: 0
        softFail: true
      batteryWeight:
        type: Number
        optional: true
        description: Weight of the battery if it contributes to the dangerous goods classification, in kilograms.
        minValue: "0.001"
        maxScale: 3
        softFail: true
