name: urn:sib:product-images-1
version: 1
state: Active
description: Provides various images for a product.
fields:
  images:
    type: List
    description: Lists all images available for a product.
    contents: 
      type: Object
      fields:
        label:
          type: String
          description: |
            Might contain a label or short and concise description of the image.
            Cryptic filenames like acme_coloured_v99_453486.img should be avoided.          
          translated: true
          optional: true
        type:
          type: String
          description: Contains the type of image being supplied.
          softFail: true
          choices:
            # Product image - DQR: B_, BMDG: P01
            - COLORED_IMAGE
            # Product image (black & white) - DQR: S_
            - BW_IMAGE
            # Dimensioned drawing - DQR: V_, BMDG: P08
            - MEASURED_DRAWING
            # Exploded drawing - DQR: X_, BMDG: P10
            - EXPLODED_DRAWING
            # Line drawing - DQR: U_, BMDG: P07
            - DRAWING
            # Detailed view - DQR: DT, BMDG: P13
            - DETAILED_IMAGE
            # Logo - DQR: LO, BMDG: P05
            - LOGO
            # Pictogram/Icon
            - ICON
            # Energy icon
            - ERP_ICON
            # Seal of approval
            - SEAL_OF_APPROVAL
        image:
          type: Asset
          description: Contains the name or path of the asset to use as image.          
          acceptedFileExtensions:
            - jpg
            - jpeg
            - png
            - tif
            - tiff
            - webp
            - heic
            - avif
            - pdf
        contentLanguages:
          type: List
          description: Contains the languages this image is available in, using ISO 639-1 codes (e.g. "en" for English, "de" for German).
          optional: true
          contents:
            type: String
            pattern: "[a-z]{2}"
            validationMessage: A two-letter (lowercase) ISO 639-1 language code is required.
