name: urn:sib:product-brand-1
version: 1
state: Active
description: |
  Contains some information for the brand or manufacturer of a product.
  This is most probably stored in an own block and then 'linked' to all
  products (sold via one brand - there might by several). This way, the
  information provided below, can be easily changed for all products.
fields:
  brandName:
    type: String
    description: Contains the (short) brand name under which a product is sold.
    optional: true
  brandLogo:
    type: Asset
    description: Contains the logo used for the brand.
    optional: true
    acceptedFileExtensions:
      - jpg
      - jpeg
      - png
      - tif
      - tiff
      - webp
      - heic
      - avif
  slogan:
    type: String
    description: Contains the slogan or tagline of the brand.
    translated: true
    optional: true
  website:
    type: String
    description: Contains the website URL of the brand or manufacturer. This should be a full URL including "https://".
    translated: true
    optional: true
  manufacturer:
    type: Object
    description: Contains details about the manufacturer, especially to meet GPSR regulation requirements.
    optional: true
    fields:
      name:
        type: String
        description: Should contain the full company name like ACME Inc.
        translated: true
        optional: true
      postalAddress:
        type: String
        description: Should contain the postal address. like Somestreet 1, 12345 Somecity, Somecountry.
        optional: true
      electronicAddress:
        type: String
        description: Should contain the electronic address (e.g. website, email).
        optional: true
  distributor:
    type: Object
    description: Contains details about the distributor, especially to meet GPSR regulation requirements.
    optional: true
    fields:
      name:
        type: String
        description: Should contain the full company name like ACME Inc.
        translated: true
        optional: true
      postalAddress:
        type: String
        description: Should contain the postal address. like Somestreet 1, 12345 Somecity, Somecountry.
        optional: true
      electronicAddress:
        type: String
        description: Should contain the electronic address (e.g. website, email).
        optional: true